model_id: swiss-ai/Apertus-8B-Instruct-2509

dataset_repo: LEXam-Benchmark/LEXam
subsets: 
  - mcq_4_choices
  - mcq_8_choices
  - mcq_16_choices
  - mcq_32_choices
split: test

# Regex to capture A, B, C... AA, AB...
match_choice_regex: "###([A-Z]+)###"

# vLLM context / output sizes
max_model_len: 8192
max_new_tokens: 4096

# generation
temperature: 0.0
top_p: 1.0
seed: 0

# parallelism
tensor_parallel_size: 4
pipeline_parallel_size: 1

# WandB
wandb:
  project: "LEXam-Evaluation"
  entity: "lsaie-peft-apertus"
  name: "Apertus-8B-Instruct"
