# Model
model_name_or_path: swiss-ai/Apertus-70B-Instruct-2509
# attn_implementation: kernels-community/vllm-flash-attn3
dtype: bfloat16

# Dataset
dataset_name: HuggingFaceH4/Multilingual-Thinking #rcds/swiss_judgment_prediction
dataset_num_proc: 32
from_disk: false # true
processing_strategy: default # swiss_judgment_prediction
# dataset_config: "all"

# Hyperparameters
learning_rate: 2.0e-4
gradient_checkpointing: true
num_train_epochs: 1.0
logging_steps: 1
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
bf16: true
bf16_full_eval: true

# LoRA / PEFT
use_peft: true
lora_r: 8
lora_alpha: 32
lora_dropout: 0.0
lora_target_modules: all-linear

# Seq length & scheduler
max_length: 4096
warmup_ratio: 0.0
lr_scheduler_type: constant
# lr_scheduler_kwargs:
#   min_lr_rate: 0.1

# Output & logging
output_dir: /iopsstor/scratch/cscs/dmelikidze/LSAIE/project/peft_apertus/models/apertus70B_sft_lora_tests
report_to: "wandb" 
seed: 42
save_steps: 100