# Model
model_name_or_path: swiss-ai/Apertus-8B-Instruct-2509
dtype: bfloat16

# Dataset
dataset_name: /iopsstor/scratch/cscs/dmelikidze/LSAIE/project/peft_apertus/datasets/swiss_judgment_prediction_dataset
dataset_num_proc: 32
from_disk: false
processing_strategy: swiss_judgement_prediction

# Hyperparameters
learning_rate: 1.0e-3  # LR=1e-3 for missing Full FT run
gradient_checkpointing: true
num_train_epochs: 1.0
logging_steps: 1
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
bf16: true 
bf16_full_eval: true

max_length: 4096
warmup_ratio: 0.0
lr_scheduler_type: constant

output_dir: /iopsstor/scratch/cscs/dmelikidze/LSAIE/project/peft_apertus/models/lr1e-3_r1_full_8B
report_to: "wandb"
seed: 42
save_steps: 100

# WandB configuration
run_name: lr1e-3_r1_full_8B
wandb_project: swiss_judgment_prediction

