# no sharding. replicates model, gradients, and optimizer states on every GPU.
compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: None
  offload_param_device: None
  zero3_init_flag: false
  zero_stage: 0
distributed_type: DEEPSPEED
main_training_function: main
mixed_precision: 'bf16'
same_network: true
rdzv_backend: static
use_cpu: false
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false